### ISSUE TITLE
llama2训练完一轮，进行eval时，报错。

### ISSUE THREAD

**Issue by KingMaoDou** [LIN-SHANG/InstructERC#11]
我处理的数据集是imeocap数据集。
选用的脚本是bash train_and_inference_Uni.sh（更改了BS部分的超参数）
![image](https://github.com/LIN-SHANG/InstructERC/assets/114294557/9ceadffb-1b75-49e8-a09e-2486d4f55cc7)

执行的分支是（我把epoch改成了15）
![image](https://github.com/LIN-SHANG/InstructERC/assets/114294557/1211d2e3-7a29-4b3c-8589-3fc59729d769)

我想问一下，加载完模型之后这里为什么会有四个数字？
![image](https://github.com/LIN-SHANG/InstructERC/assets/114294557/f7212c2d-9e7a-4275-a6b8-9964c1e3954c)
80这部分数据是干什么用的？

以及为什么我训练一轮进行评测时，报错
![image](https://github.com/LIN-SHANG/InstructERC/assets/114294557/354b3c98-51da-4f49-b814-be59cf652568)

**Comment by HenFo** [comment]
For your last problem: you are probably training with FP16 conversion, LLaMA2 doesn't seem to like that. Use bfloat16 instead (See [Issue](https://github.com/LIN-SHANG/InstructERC/issues/6)). As far as know, bfloat16 has to be supported by your GPU, so if that doesn't work, you can look further into this.

**Comment by dongguanting** [comment]
See [Issue](https://github.com/LIN-SHANG/InstructERC/issues/6)
