### ISSUE TITLE
三个数据集的pkl怎么生成

### ISSUE THREAD

**Issue by Yang-Liz** [LIN-SHANG/InstructERC#13]
文中提及的三个数据集的官方文件只有原始数据，如何构建pkl文件呢？
![微信图片_20240328153546](https://github.com/LIN-SHANG/InstructERC/assets/56384857/69cfb377-290d-4409-a745-23c1ccc76ba5)

**Comment by LIN-SHANG** [comment]
There are two methods to complete the construction of pkl files:
1. Download the official files of the three datasets and then extract the text files from them.
2. Utilize the text files that have been initially extracted by COSMIC. For more information, please refer to [this GitHub repository](https://github.com/declare-lab/conv-emotion/tree/master/COSMIC/feature-extraction).
