### ISSUE TITLE
Emotion prediction task is added to main task

### ISSUE THREAD

**Issue by xiaofen011** [LIN-SHANG/InstructERC#5]
Do the following code blocks need to be modified?
![微信图片_20231127210429](https://github.com/LIN-SHANG/InstructERC/assets/152181867/0fd2382d-976e-46a2-9a73-1e011cf3a212)

**Comment by graciechen** [comment]
> Do the following code blocks need to be modified? ![微信图片_20231127210429](https://private-user-images.githubusercontent.com/152181867/285871141-0fd2382d-976e-46a2-9a73-1e011cf3a212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTQwNjAsIm5iZiI6MTcwNTM5Mzc2MCwicGF0aCI6Ii8xNTIxODE4NjcvMjg1ODcxMTQxLTBmZDIzODJkLTk3NmUtNDZhMi05YTczLTFlMDExY2YzYTIxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwODI5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2IyYzdjMmM4NGFkNzZjNWMwZmNhZjY5YzliNTkwN2RiMTNhZmVhYjhiYmUzYTY1YjllNTc5ZGMzNjhiZDBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lCphgY0iVjGeGkLERl5bjJCh8uLhJMXn3P0lNzi7pNo)

这段现在注释掉了

**Comment by Paxelrod-web** [comment]
我看了一下数据集的构成，在进行emotion prediction时，是将两个语句是拼起来一起训练的，loss本身就已经包含了emotion prediction，感觉不用重新计算。不知道我的理解对不对，错了的话希望帮忙指正一下

**Comment by graciechen** [comment]
> 我看了一下数据集的构成，在进行emotion prediction时，是将两个语句是拼起来一起训练的，loss本身就已经包含了emotion prediction，感觉不用重新计算。不知道我的理解对不对，错了的话希望帮忙指正一下



> 我看了一下数据集的构成，在进行emotion prediction时，是将两个语句是拼起来一起训练的，loss本身就已经包含了emotion prediction，感觉不用重新计算。不知道我的理解对不对，错了的话希望帮忙指正一下
 是的，代码里loss就是模型的loss，和论文中提到的main task的loss和 prediction 的kl loss权重 loss 不太一致
